stages:
  data-prep:
    cmd: python src/02_data_prep.py
    deps:
    - data/recruitment_details.csv  
    - src/02_data_prep.py
    outs:
    - data/prepared_data.csv
  train:
    cmd: python src/03_train.py
    deps:
    - data/prepared_data.csv
    - src/03_train.py
    metrics:
    - data/metrics.json:
        cache: false
